"""Codex CLI runner for SRE investigations.

Launches `codex exec --json` as a subprocess, streams events,
and records spans in Langfuse.
"""

import asyncio
import json
import os
import shutil

import structlog

from agent.app.config import settings
from agent.app.langfuse_tracer import InvestigationTracer
from agent.app.mcp_tools.telegram_send import send_report

logger = structlog.get_logger()


def _build_prompt(alert: dict) -> str:
    """Build Codex prompt from Zabbix alert data.

    Args:
        alert: Dict with alert_id, host, trigger, severity, timestamp, description.

    Returns:
        Formatted prompt string for Codex.
    """
    return f"""Получен алерт от Zabbix:
- Host: {alert['host']}
- Trigger: {alert['trigger']}
- Severity: {alert['severity']}
- Время: {alert['timestamp']}
- Описание: {alert['description']}

Проведи диагностику. Используй доступные команды терминала через SSH к серверу playground.
При необходимости найди релевантный Runbook через инструмент qdrant_search.
По завершении отправь отчёт через telegram_send."""


CODEX_WORKDIR = "/opt/codex_workdir"


def _codex_env() -> dict[str, str]:
    """Build environment variables for Codex subprocess.

    Codex 0.117+ reads provider config from config.toml (not env vars).
    We only pass the API key env var that config.toml references via env_key.

    Returns:
        Dict of env vars for Codex subprocess.
    """
    env = os.environ.copy()
    # RMR_API_KEY is referenced by config.toml [model_providers.rmrouter].env_key
    # Already set via docker-compose env_file, but ensure it's present
    if "RMR_API_KEY" not in env:
        env["RMR_API_KEY"] = settings.gateway_api_key
    # Remove deprecated vars that cause warnings
    env.pop("OPENAI_BASE_URL", None)
    return env


async def run_investigation(
    alert: dict,
    investigation_id: str,
    tracer: InvestigationTracer,
) -> str:
    """Run a full Codex investigation for a Zabbix alert.

    Launches codex exec, parses JSON events, records Langfuse spans,
    and returns the final report.

    If Codex CLI is not available, falls back to a simulated investigation
    using direct LLM calls via httpx.

    Args:
        alert: Zabbix alert data dict.
        investigation_id: Unique investigation identifier.
        tracer: Langfuse tracer for this investigation.

    Returns:
        Investigation report text.
    """
    prompt = _build_prompt(alert)
    codex_path = shutil.which("codex")

    if codex_path:
        report = await _run_with_codex(prompt, investigation_id, tracer)
        # If Codex produced a real report, use it
        if report and report != "No report generated by Codex":
            return report
        # Otherwise fall through to fallback with SSH diagnostics
        logger.info("codex_empty_report_using_fallback", investigation_id=investigation_id)

    if not codex_path:
        logger.warning("codex_not_found_using_fallback", investigation_id=investigation_id)

    return await _run_fallback(prompt, alert, investigation_id, tracer)


async def _run_with_codex(
    prompt: str,
    investigation_id: str,
    tracer: InvestigationTracer,
) -> str:
    """Run investigation using Codex CLI.

    Uses -o flag to capture last agent message to a file,
    and --json for event tracing in Langfuse.

    Args:
        prompt: Investigation prompt.
        investigation_id: Investigation ID.
        tracer: Langfuse tracer.

    Returns:
        Final report text from Codex.
    """
    output_file = f"/tmp/codex_report_{investigation_id}.txt"
    cmd = [
        "codex", "exec",
        "--full-auto",
        "--model", settings.codex_model,
        "--sandbox", "danger-full-access",
        "-o", output_file,
        prompt,
    ]

    # Ensure git repo exists in codex workdir (required by Codex CLI)
    if not os.path.exists(os.path.join(CODEX_WORKDIR, ".git")):
        await asyncio.create_subprocess_exec(
            "git", "init", cwd=CODEX_WORKDIR,
            stdout=asyncio.subprocess.DEVNULL, stderr=asyncio.subprocess.DEVNULL,
        )

    logger.info("codex_starting", investigation_id=investigation_id, model=settings.codex_model)

    process = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        env=_codex_env(),
        cwd=CODEX_WORKDIR,
    )

    try:
        async with asyncio.timeout(settings.investigation_timeout_seconds):
            stdout, stderr = await process.communicate()
    except TimeoutError:
        logger.error("codex_timeout", investigation_id=investigation_id)
        process.kill()
        tracer.finish(status="timeout")
        return "Investigation timed out"

    # Read report from output file
    report = ""
    try:
        with open(output_file) as f:
            report = f.read().strip()
        os.unlink(output_file)
    except FileNotFoundError:
        pass

    if not report:
        report = "No report generated by Codex"

    logger.info(
        "codex_finished",
        investigation_id=investigation_id,
        exit_code=process.returncode,
        report_length=len(report),
    )

    # Record in Langfuse
    tracer.span_llm_call(
        model=settings.codex_model,
        input_text=prompt[:500],
        output_text=report[:2000],
    )

    return report


async def _ssh_cmd(cmd: str) -> tuple[int, str]:
    """Execute a command on playground via SSH.

    Args:
        cmd: Shell command to execute.

    Returns:
        Tuple of (exit_code, stdout_truncated).
    """
    ssh_args = [
        "ssh",
        "-o", "StrictHostKeyChecking=no",
        "-o", "UserKnownHostsFile=/dev/null",
        "-o", "LogLevel=ERROR",
        "-i", settings.playground_ssh_key_path,
        f"{settings.playground_ssh_user}@{settings.playground_ssh_host}",
        cmd,
    ]
    try:
        proc = await asyncio.create_subprocess_exec(
            *ssh_args,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )
        async with asyncio.timeout(30):
            stdout, _ = await proc.communicate()
        output = stdout.decode("utf-8", errors="replace")[:4000]
        return proc.returncode or 0, output
    except TimeoutError:
        proc.kill()
        return 1, "[command timed out after 30s]"
    except Exception as exc:
        return 1, f"[SSH error: {exc}]"


# Diagnostic commands by alert trigger keyword
DIAGNOSTIC_COMMANDS: dict[str, list[str]] = {
    "cpu": [
        "top -bn1 | head -20",
        "ps aux --sort=-%cpu | head -10",
        "uptime",
    ],
    "memory": [
        "free -h",
        "ps aux --sort=-%mem | head -10",
        "cat /proc/meminfo | head -10",
    ],
    "disk": [
        "df -h",
        "du -sh /var/log/* 2>/dev/null | sort -rh | head -10",
        "du -sh /tmp/* 2>/dev/null | sort -rh | head -5",
    ],
    "redis": [
        "redis-cli INFO memory 2>/dev/null || echo 'redis-cli not available'",
        "redis-cli DBSIZE 2>/dev/null || echo 'redis-cli not available'",
    ],
    "down": [
        "docker ps -a 2>/dev/null || echo 'docker not available'",
        "netstat -tlnp 2>/dev/null || ss -tlnp",
    ],
}


async def _run_ssh_diagnostics(alert: dict, tracer: InvestigationTracer) -> str:
    """Run diagnostic SSH commands based on alert trigger keywords.

    Args:
        alert: Zabbix alert dict with 'trigger' field.
        tracer: Langfuse tracer.

    Returns:
        Formatted string with command results.
    """
    trigger = alert.get("trigger", "").lower()

    # Select commands based on trigger keywords
    commands = ["uptime", "free -h", "df -h"]  # always run basics
    for keyword, cmds in DIAGNOSTIC_COMMANDS.items():
        if keyword in trigger:
            commands.extend(cmds)

    # Deduplicate while preserving order
    seen: set[str] = set()
    unique_commands: list[str] = []
    for cmd in commands:
        if cmd not in seen:
            seen.add(cmd)
            unique_commands.append(cmd)

    results: list[str] = []
    for cmd in unique_commands[:settings.max_shell_commands]:
        exit_code, output = await _ssh_cmd(cmd)
        results.append(f"$ {cmd}\n{output.strip()}\n(exit_code={exit_code})")
        tracer.span_shell_command(
            command=cmd,
            exit_code=exit_code,
            stdout=output,
        )
        logger.info("ssh_command", command=cmd, exit_code=exit_code)

    return "\n\n".join(results)


async def _run_fallback(
    prompt: str,
    alert: dict,
    investigation_id: str,
    tracer: InvestigationTracer,
) -> str:
    """Fallback investigation using direct LLM calls (no Codex CLI).

    Makes a single LLM call through LiteLLM Gateway to generate
    a diagnostic report based on the alert data.

    Args:
        prompt: Investigation prompt.
        alert: Zabbix alert data dict.
        investigation_id: Investigation ID.
        tracer: Langfuse tracer.

    Returns:
        Generated report text.
    """
    import httpx

    from agent.app.mcp_tools.qdrant_search import search as qdrant_search

    logger.info("fallback_investigation_starting", investigation_id=investigation_id)

    # Step 1: Search runbooks
    runbook_context = ""
    try:
        runbook_context = qdrant_search(alert["trigger"])
        tracer.span_tool_call("qdrant_search", alert["trigger"], runbook_context[:500])
        logger.info("runbook_found", investigation_id=investigation_id)
    except Exception as exc:
        logger.warning("runbook_search_failed", error=str(exc))

    # Step 2: Run SSH diagnostic commands
    ssh_results = await _run_ssh_diagnostics(alert, tracer)

    # Step 3: Call LLM via Gateway with real diagnostic data
    system_prompt = """Ты — L1 SRE-агент. Проанализируй результаты диагностики и сформируй отчёт:
1. Краткое описание инцидента
2. Ключевые находки из диагностики
3. Root cause (гипотеза)
4. Рекомендации по исправлению
5. Ссылка на Runbook (если найден)"""

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": prompt},
    ]
    if ssh_results:
        messages.append({
            "role": "user",
            "content": f"Результаты SSH-диагностики:\n{ssh_results[:3000]}",
        })
    if runbook_context:
        messages.append({
            "role": "user",
            "content": f"Контекст из Runbook:\n{runbook_context[:2000]}",
        })

    report = "Investigation failed — no LLM response"
    try:
        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post(
                f"{settings.gateway_url}/v1/chat/completions",
                headers={"Authorization": f"Bearer {settings.gateway_api_key}"},
                json={
                    "model": settings.codex_model,
                    "messages": messages,
                    "max_tokens": 2000,
                    "temperature": 0.3,
                },
            )
            if resp.status_code == 200:
                data = resp.json()
                choices = data.get("choices", [])
                if choices:
                    report = choices[0].get("message", {}).get("content", "") or report
                usage = data.get("usage", {})
                tracer.span_llm_call(
                    model=settings.codex_model,
                    input_text=prompt[:500],
                    output_text=report[:500],
                    tokens_in=usage.get("prompt_tokens", 0),
                    tokens_out=usage.get("completion_tokens", 0),
                )
            else:
                logger.error("llm_call_failed", status=resp.status_code, body=resp.text[:200])
    except Exception as exc:
        logger.error("llm_call_error", error=str(exc))

    return report
